#!/bin/bash

# Author: Robert H Cudmore
# Date: 20181203
#
# Build a stand-alone app using pyinstaller

#  -D, --onedir          Create a one-folder bundle containing an executable
#                        (default)
#
#  -F, --onefile         Create a one-file bundled executable.
#
#  -w, --windowed, --noconsole
#                        Windows and Mac OS X: do not provide a console window
#                        for standard i/o. On Mac OS X this also triggers
#                        building an OS X .app bundle. This option is ignored
#                        in *NIX systems.
#

rm -rf build dist

# get current date-time
dt=$(date '+%Y%m%d_%H%M%S');

# need to use commander2 or else bundle dir (in python) is always user dir?
#pyinstaller -w --onefile --add-data "templates:templates" --add-data "static:static" --add-data "config:config" --add-data "bin:bin" commander.py
commander_env/bin/pyinstaller -F --add-data "templates:templates" --add-data "static:static" --add-data "config:config" --add-data "bin:bin" -n commander_$dt commander2.py
